version: 2

models:
  - name: stg_btc
    columns:
      - name: HASH_KEY
        tests:
          - not_null
          - unique



exposures:
  - name: btc_whale_alert_exposure
    label: BTC Whale Alert
    type: dashboard
    maturity: high
    url: https://datastudio.google.com/reporting/ac9754c8-c05c-4518-bb8e-d945582a62bf/page/YF37F
    description: >
      BTC Whale alert transactions report

    depends_on:
      - ref('whale_alert')

    owner:
      name: Selvakumar Boominathan
  - name: whale_alert
    latest_version: 1
    config:
      contract:
        enforced: true
    columns:
      - name: TX_COUNT
        data_type: integer
      - name: TOTAL_SENT
        data_type: float
      - name: PRICE
        data_type: float
      - name: output_address
        data_type: string
        tests:
          - assert_valid_btc_address
    versions:

      -v: 1

      -v: 2
      columns:
          - include: all
            exclude: [PRICE]
